services:
  - type: web
    name: kerm-lite-2
    env: node
    branch: main
    repo: https://github.com/kgtech-cmr/KERM-LITE-2.git
    buildCommand: npm install
    startCommand: npm start
    plan: free
    autoDeploy: false
    envVars:
      - key: SESSION_ID
        sync: false
      - key: DATABASE_URL
        sync: false
